import { Route } from "next";
import {
    FaHammer,
    FaPaintRoller,
    FaToilet,
    FaPlug,
    FaWrench,
    FaDoorOpen,
    FaScrewdriver,
    FaLeaf,
    FaSquare,
    FaUtensils,
    FaBlender,
    FaSpa,
    FaDumbbell,
    FaPaintBrush,
    FaShower,
    FaChair,
    FaLightbulb,
    FaTools,
    FaWindowMaximize
} from 'react-icons/fa';

import { IconType } from "react-icons";

export interface CategoryItemType {
    id: string;
    name: string;
    href: string;
    slug: string;
    icon?: IconType;
    description?: string;
    featured?: boolean;
    subcategories?: CategoryItemType[];
    imageUrl?: string;
    itemCount?: number;
    stats?: {
        products: number;
        views: number;
        rating: number;
    };
    badges?: string[];
    lastUpdated?: string;
    trendingScore?: number;
}


export const CATEGORIES: CategoryItemType[] = [
    {
        id: 'cat-building-materials',
        name: 'Строительные материалы',
        href: '/category/building-materials',
        slug: 'building-materials',
        icon: FaHammer,
        description: 'Основные строительные материалы высокого качества для любых строительных проектов',
        featured: true,
        imageUrl: 'https://www.a-mortar.ru/upload/images/kr-gl_1800x530_1f1.jpg',
        itemCount: 156,
        stats: { products: 156, views: 4500, rating: 4.8 },
        badges: ['Популярное', 'Новинка'],
        lastUpdated: '2024-12-20',
        trendingScore: 95,
        subcategories: [
            {
                id: 'subcat-cement',
                name: 'Цемент',
                href: '/category/building-materials/cement',
                slug: 'cement',
                description: 'Портландцемент и специальные цементные смеси',
                itemCount: 24,
                stats: { products: 24, views: 1200, rating: 4.5 },
                badges: ['Рекомендуется'],
                trendingScore: 88
            },
            {
                id: 'subcat-sand',
                name: 'Песок',
                href: '/category/building-materials/sand',
                slug: 'sand',
                description: 'Строительный песок различных фракций',
                itemCount: 12,
                stats: { products: 12, views: 800, rating: 4.3 },
                trendingScore: 72
            },
            {
                id: 'subcat-gravel',
                name: 'Щебень',
                href: '/category/building-materials/gravel',
                slug: 'gravel',
                description: 'Щебень разных фракций и материалов',
                itemCount: 18,
                stats: { products: 18, views: 900, rating: 4.4 },
                trendingScore: 76
            },
            {
                id: 'subcat-brick',
                name: 'Кирпич',
                href: '/category/building-materials/brick',
                slug: 'brick',
                description: 'Облицовочный и строительный кирпич',
                itemCount: 102,
                stats: { products: 102, views: 2000, rating: 4.7 },
                badges: ['Бестселлер'],
                trendingScore: 90
            }
        ]
    },
    {
        id: 'cat-finishing-materials',
        name: 'Отделочные материалы',
        href: '/category/finishing-materials',
        slug: 'finishing-materials',
        icon: FaPaintRoller,
        description: 'Широкий выбор материалов для внутренней и внешней отделки',
        featured: true,
        imageUrl: 'https://tulatrud.ru/800/600/https/rehouz.info/wp-content/uploads/2018/05/%D0%92%D0%B8%D0%B4%D1%8B-%D0%B4%D0%B5%D0%BA%D0%BE%D1%80%D0%B0%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BA%D0%B0%D0%BC%D0%BD%D1%8F.jpg',
        itemCount: 284,
        stats: { products: 284, views: 5200, rating: 4.9 },
        badges: ['Тренд'],
        lastUpdated: '2024-12-19',
        trendingScore: 92,
        subcategories: [
            {
                id: 'subcat-laminate',
                name: 'Ламинат',
                href: '/category/finishing-materials/laminate',
                slug: 'laminate',
                description: 'Ламинат различных классов износостойкости',
                itemCount: 86,
                stats: { products: 86, views: 2200, rating: 4.8 },
                badges: ['Популярное'],
                trendingScore: 93
            },
            {
                id: 'subcat-tiles',
                name: 'Плитка',
                href: '/category/finishing-materials/tiles',
                slug: 'tiles',
                description: 'Керамическая плитка и керамогранит',
                itemCount: 124,
                stats: { products: 124, views: 3000, rating: 4.7 },
                badges: ['Рекомендуется'],
                trendingScore: 95
            },
            {
                id: 'subcat-wallpaper',
                name: 'Обои',
                href: '/category/finishing-materials/wallpaper',
                slug: 'wallpaper',
                description: 'Виниловые, флизелиновые и бумажные обои',
                itemCount: 98,
                stats: { products: 98, views: 2500, rating: 4.6 },
                trendingScore: 89
            },
            {
                id: 'subcat-paint',
                name: 'Краска',
                href: '/category/finishing-materials/paint',
                slug: 'paint',
                description: 'Краски для внутренних и наружных работ',
                itemCount: 76,
                stats: { products: 76, views: 1800, rating: 4.5 },
                trendingScore: 85
            }
        ]
    },
    {
        id: 'cat-bathroom',
        name: 'Ванная комната',
        href: '/category/bathroom',
        slug: 'bathroom',
        icon: FaShower,
        description: 'Товары для обустройства ванной комнаты',
        featured: true,
        imageUrl: 'https://www.eremont.ru/upload/iblock/4c9/jkm1n3bazulicjaz54p59dmabzmkhh62/CHasha-vanny-iz-iskusstvennogo-kamnya-i-rakovina-v-tom-zhe-stile.jpg',
        itemCount: 198,
        stats: {
            products: 198,
            views: 5120,
            rating: 4.7,
        },
        badges: ['Популярное', 'Рекомендуем'],
        lastUpdated: '2024-12-15',
        trendingScore: 85,
        subcategories: [
            {
                id: 'subcat-shower-cabins',
                name: 'Душевые кабины',
                href: '/category/bathroom/shower-cabins',
                slug: 'shower-cabins',
                description: 'Современные и удобные душевые кабины',
                itemCount: 78,
                stats: {
                    products: 78,
                    views: 1023,
                    rating: 4.8,
                },
                badges: ['Новинка'],
                lastUpdated: '2024-12-12',
                trendingScore: 70,
            },
            {
                id: 'subcat-bathroom-cabinets',
                name: 'Тумбы для ванной',
                href: '/category/bathroom/cabinets',
                slug: 'bathroom-cabinets',
                description: 'Эстетичные и функциональные тумбы',
                itemCount: 56,
                stats: {
                    products: 56,
                    views: 891,
                    rating: 4.5,
                },
                badges: ['Скидки'],
                lastUpdated: '2024-12-10',
                trendingScore: 65,
            },
            {
                id: 'subcat-mirrors',
                name: 'Зеркала',
                href: '/category/bathroom/mirrors',
                slug: 'mirrors',
                description: 'Зеркала с подсветкой и без',
                itemCount: 34,
                stats: {
                    products: 34,
                    views: 670,
                    rating: 4.6,
                },
                badges: ['Акция'],
                lastUpdated: '2024-12-08',
                trendingScore: 55,
            },
            {
                id: 'subcat-accessories',
                name: 'Аксессуары для ванной',
                href: '/category/bathroom/accessories',
                slug: 'accessories',
                description: 'Полотенцедержатели, дозаторы, коврики и другое',
                itemCount: 56,
                stats: {
                    products: 56,
                    views: 984,
                    rating: 4.7,
                },
                badges: ['Рекомендуем'],
                lastUpdated: '2024-12-14',
                trendingScore: 72,
            },
        ],
    },
    {
        id: 'cat-office-furniture',
        name: 'Офисная мебель',
        href: '/category/office-furniture',
        slug: 'office-furniture',
        icon: FaChair,
        description: 'Эргономичная мебель для вашего офиса',
        featured: false,
        imageUrl: '/images/category/office-furniture.jpg',
        itemCount: 145,
        stats: {
            products: 145,
            views: 3120,
            rating: 4.6,
        },
        badges: ['Эргономика', 'Рекомендуем'],
        lastUpdated: '2024-12-13',
        trendingScore: 68,
        subcategories: [
            {
                id: 'subcat-desks',
                name: 'Столы',
                href: '/category/office-furniture/desks',
                slug: 'desks',
                description: 'Рабочие и компьютерные столы',
                itemCount: 56,
                stats: {
                    products: 56,
                    views: 721,
                    rating: 4.4,
                },
                badges: ['Популярное'],
                lastUpdated: '2024-12-09',
                trendingScore: 62,
            },
            {
                id: 'subcat-chairs',
                name: 'Кресла',
                href: '/category/office-furniture/chairs',
                slug: 'chairs',
                description: 'Офисные кресла и стулья',
                itemCount: 68,
                stats: {
                    products: 68,
                    views: 1056,
                    rating: 4.7,
                },
                badges: ['Рекомендуем'],
                lastUpdated: '2024-12-11',
                trendingScore: 78,
            },
            {
                id: 'subcat-storage',
                name: 'Системы хранения',
                href: '/category/office-furniture/storage',
                slug: 'storage',
                description: 'Шкафы и стеллажи для офиса',
                itemCount: 34,
                stats: {
                    products: 34,
                    views: 520,
                    rating: 4.3,
                },
                badges: ['Новинка'],
                lastUpdated: '2024-12-08',
                trendingScore: 55,
            },
        ],
    },
    {
        id: 'cat-lighting',
        name: 'Освещение',
        href: '/category/lighting',
        slug: 'lighting',
        icon: FaLightbulb,
        description: 'Современные решения для освещения',
        featured: true,
        imageUrl: 'https://vestnikao.ru/wp-content/uploads/2021/07/1-osveshhenie.jpg',
        itemCount: 276,
        stats: {
            products: 276,
            views: 4820,
            rating: 4.8,
        },
        badges: ['Популярное', 'Новинка'],
        lastUpdated: '2024-12-15',
        trendingScore: 90,
        subcategories: [
            {
                id: 'subcat-ceiling-lights',
                name: 'Потолочные светильники',
                href: '/category/lighting/ceiling-lights',
                slug: 'ceiling-lights',
                description: 'Эстетичные потолочные светильники для любого интерьера',
                itemCount: 96,
                stats: {
                    products: 96,
                    views: 1123,
                    rating: 4.7,
                },
                badges: ['Рекомендуем'],
                lastUpdated: '2024-12-12',
                trendingScore: 75,
            },
            {
                id: 'subcat-wall-lights',
                name: 'Настенные светильники',
                href: '/category/lighting/wall-lights',
                slug: 'wall-lights',
                description: 'Настенные бра для уюта и стиля',
                itemCount: 78,
                stats: {
                    products: 78,
                    views: 1034,
                    rating: 4.6,
                },
                badges: ['Акция'],
                lastUpdated: '2024-12-10',
                trendingScore: 70,
            },
            {
                id: 'subcat-table-lamps',
                name: 'Настольные лампы',
                href: '/category/lighting/table-lamps',
                slug: 'table-lamps',
                description: 'Функциональные настольные лампы для работы и чтения',
                itemCount: 54,
                stats: {
                    products: 54,
                    views: 860,
                    rating: 4.5,
                },
                badges: ['Скидки'],
                lastUpdated: '2024-12-09',
                trendingScore: 68,
            },
            {
                id: 'subcat-outdoor-lights',
                name: 'Уличное освещение',
                href: '/category/lighting/outdoor-lights',
                slug: 'outdoor-lights',
                description: 'Прочные и стильные светильники для улицы',
                itemCount: 48,
                stats: {
                    products: 48,
                    views: 724,
                    rating: 4.4,
                },
                badges: ['Новинка'],
                lastUpdated: '2024-12-14',
                trendingScore: 60,
            },
        ],
    },
    {
        id: 'cat-kitchen-appliances',
        name: 'Кухонная техника',
        href: '/category/kitchen-appliances',
        slug: 'kitchen-appliances',
        icon: FaBlender,
        description: 'Умная и функциональная техника для кухни',
        featured: true,
        imageUrl: 'https://design-homes.ru/images/galery/2629/bespoleznaya-tekhnika-dlya-kukhni_5fda6cc47341d.jpg',
        itemCount: 325,
        stats: {
            products: 325,
            views: 5620,
            rating: 4.9,
        },
        badges: ['Топ продаж', 'Рекомендуем'],
        lastUpdated: '2024-12-15',
        trendingScore: 95,
        subcategories: [
            {
                id: 'subcat-coffee-machines',
                name: 'Кофемашины',
                href: '/category/kitchen-appliances/coffee-machines',
                slug: 'coffee-machines',
                description: 'Идеальные кофемашины для дома и офиса',
                itemCount: 112,
                stats: {
                    products: 112,
                    views: 1345,
                    rating: 4.9,
                },
                badges: ['Рекомендуем'],
                lastUpdated: '2024-12-11',
                trendingScore: 85,
            },
            {
                id: 'subcat-microwaves',
                name: 'Микроволновые печи',
                href: '/category/kitchen-appliances/microwaves',
                slug: 'microwaves',
                description: 'Быстрая и удобная техника для разогрева еды',
                itemCount: 84,
                stats: {
                    products: 84,
                    views: 1023,
                    rating: 4.8,
                },
                badges: ['Новинка'],
                lastUpdated: '2024-12-10',
                trendingScore: 75,
            },
            {
                id: 'subcat-blenders',
                name: 'Блендеры',
                href: '/category/kitchen-appliances/blenders',
                slug: 'blenders',
                description: 'Идеально для приготовления смузи и коктейлей',
                itemCount: 72,
                stats: {
                    products: 72,
                    views: 935,
                    rating: 4.7,
                },
                badges: ['Популярное'],
                lastUpdated: '2024-12-09',
                trendingScore: 70,
            },
            {
                id: 'subcat-toasters',
                name: 'Тостеры',
                href: '/category/kitchen-appliances/toasters',
                slug: 'toasters',
                description: 'Удобные и стильные тостеры для завтрака',
                itemCount: 57,
                stats: {
                    products: 57,
                    views: 820,
                    rating: 4.6,
                },
                badges: ['Акция'],
                lastUpdated: '2024-12-13',
                trendingScore: 65,
            },
        ],
    },
    {
        id: 'cat-personal-care',
        name: 'Уход за собой',
        href: '/category/personal-care',
        slug: 'personal-care',
        icon: FaSpa,
        description: 'Техника для здоровья и красоты',
        featured: false,
        imageUrl: '/images/category/personal-care.jpg',
        itemCount: 198,
        stats: {
            products: 198,
            views: 4210,
            rating: 4.7,
        },
        badges: ['Рекомендуем', 'Популярное'],
        lastUpdated: '2024-12-15',
        trendingScore: 80,
        subcategories: [
            {
                id: 'subcat-hair-dryers',
                name: 'Фены для волос',
                href: '/category/personal-care/hair-dryers',
                slug: 'hair-dryers',
                description: 'Качественные фены для профессиональной укладки',
                itemCount: 85,
                stats: {
                    products: 85,
                    views: 1230,
                    rating: 4.8,
                },
                badges: ['Топ продаж'],
                lastUpdated: '2024-12-10',
                trendingScore: 72,
            },
            {
                id: 'subcat-electric-shavers',
                name: 'Электробритвы',
                href: '/category/personal-care/electric-shavers',
                slug: 'electric-shavers',
                description: 'Современные бритвы для комфортного бритья',
                itemCount: 62,
                stats: {
                    products: 62,
                    views: 1030,
                    rating: 4.7,
                },
                badges: ['Популярное'],
                lastUpdated: '2024-12-11',
                trendingScore: 68,
            },
            {
                id: 'subcat-massagers',
                name: 'Массажеры',
                href: '/category/personal-care/massagers',
                slug: 'massagers',
                description: 'Расслабление и забота о здоровье с массажерами',
                itemCount: 51,
                stats: {
                    products: 51,
                    views: 850,
                    rating: 4.6,
                },
                badges: ['Рекомендуем'],
                lastUpdated: '2024-12-12',
                trendingScore: 65,
            },
        ],
    },
    {
        id: 'cat-sports-equipment',
        name: 'Спортивное оборудование',
        href: '/category/sports-equipment',
        slug: 'sports-equipment',
        icon: FaDumbbell,
        description: 'Все для тренировок дома и в зале',
        featured: true,
        imageUrl: 'https://tse1.mm.bing.net/th?id=OIP.7rJS8RTUyBuDKkCUIJaYFAHaFj&pid=Api',
        itemCount: 310,
        stats: {
            products: 310,
            views: 5400,
            rating: 4.8,
        },
        badges: ['Новинка', 'Рекомендуем'],
        lastUpdated: '2024-12-15',
        trendingScore: 88,
        subcategories: [
            {
                id: 'subcat-treadmills',
                name: 'Беговые дорожки',
                href: '/category/sports-equipment/treadmills',
                slug: 'treadmills',
                description: 'Эффективные тренировки дома с беговыми дорожками',
                itemCount: 105,
                stats: {
                    products: 105,
                    views: 1400,
                    rating: 4.9,
                },
                badges: ['Рекомендуем'],
                lastUpdated: '2024-12-11',
                trendingScore: 80,
            },
            {
                id: 'subcat-dumbbells',
                name: 'Гантели',
                href: '/category/sports-equipment/dumbbells',
                slug: 'dumbbells',
                description: 'Универсальное оборудование для силовых тренировок',
                itemCount: 90,
                stats: {
                    products: 90,
                    views: 1220,
                    rating: 4.7,
                },
                badges: ['Популярное'],
                lastUpdated: '2024-12-10',
                trendingScore: 75,
            },
            {
                id: 'subcat-yoga-mats',
                name: 'Коврики для йоги',
                href: '/category/sports-equipment/yoga-mats',
                slug: 'yoga-mats',
                description: 'Идеальные коврики для йоги и фитнеса',
                itemCount: 75,
                stats: {
                    products: 75,
                    views: 960,
                    rating: 4.6,
                },
                badges: ['Новинка'],
                lastUpdated: '2024-12-09',
                trendingScore: 70,
            },
            {
                id: 'subcat-punching-bags',
                name: 'Боксерские груши',
                href: '/category/sports-equipment/punching-bags',
                slug: 'punching-bags',
                description: 'Развивайте навыки бокса с профессиональным оборудованием',
                itemCount: 40,
                stats: {
                    products: 40,
                    views: 720,
                    rating: 4.5,
                },
                badges: ['Акция'],
                lastUpdated: '2024-12-13',
                trendingScore: 60,
            },
        ],
    },



    // Additional categories will follow the same format...
];

